rg_name             = "cmtr-5f0gvlzp-mod3-rg"
location            = "East US"
storageaccount_name = "cmtr5f0gvlzpsa1747111297"
vnet_name           = "cmtr-5f0gvlzp-mod3-vnet"
subnet1_name        = "frontend"
subnet2_name        = "backend"
creator_tag         = "sanjana_singh1@epam.com"
